version: '2'
services:
    moveapphipster-app:
        image: moveapphipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://moveapphipster-postgresql:5432/MoveAppHipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    moveapphipster-postgresql:
        extends:
            file: postgresql.yml
            service: moveapphipster-postgresql
